GET http://localhost:3000/customers

###
GET http://localhost:3000/customers/683906c8cd03ea53437c4f13

###
PUT http://localhost:3000/customers/683906c8cd03ea53437c4f13
content-type: application/json

{
  "firstName": "Roberto",
  "lastName": "Garcia",
  "email": "roberto@example.com",
  "phone": "123-123-4567"
}

###
POST http://localhost:3000/customers/
content-type: application/json

{
  "firstName": "",
  "lastName": "TortaPatel",
  "email": "luisito@example.com",
  "phone": "555-123-4567"
}

###
GET http://localhost:3000/products

###
GET http://localhost:3000/products/68390865cd03ea53437c4f14

###
PUT http://localhost:3000/products/68390865cd03ea53437c4f14
content-type: application/json

{
  "name": "Tablet 270",
  "brand": "Samsung",
  "price": 60,
  "stock": 50,
  "category": "Electronics",
  "isAvailable": false,
  "specifications": "64 GB of Memory Ram"
}