GET http://localhost:3000/customers

###
GET http://localhost:3000/customers/683a03afc590030515ce1520

###
PUT http://localhost:3000/customers/683906c8cd03ea53437c4f13
content-type: application/json

{
  "firstName": "Roberto",
  "lastName": "Garcia",
  "email": "roberto@example.com",
  "phone": "123-123-4567"
}

###
POST http://localhost:3000/customers/
content-type: application/json

{
  "firstName": "",
  "lastName": "TortaPatel",
  "email": "luisito@example.com",
  "phone": "555-123-4567"
}

###
GET http://localhost:3000/products

###
GET http://localhost:3000/products/68390865cd03ea53437c4f14

###
PUT http://localhost:3000/products/68390865cd03ea53437c4f14
content-type: application/json

{
  "name": "Smartphone X",
    "brand": "TechMaster",
    "price": 699.99,
    "stock": 45,
    "category": "Electronics",
    "isAvailable": true,
    "specifications": "64 giba of Ram"
}

###
POST http://localhost:3000/products/
content-type: application/json

{
  "name": "Telefono Iphone 15",
    "brand": "Iphone",
    "price": 1000,
    "stock": 45,
    "category": "Electronics",
    "isAvailable": true,
    "specifications": "64 giba of Ram"
}